apiVersion: v1
kind: ConfigMap
metadata:
  name: counter-cm
  labels:
    name: counter-cm
data:
  script.sh: |-
    cd app/
    touch counter.txt
    declare -i var=$(cat counter.txt)
    for (( ; ; ))
    do
        cat counter.txt   
        var=$((var + 1))
        echo $var >counter.txt    
        sleep 1s
    done
