apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: "amine250/counter:latest"
        volumeMounts:
        - name: counter
          mountPath: /app/
        - name: counter-script
          mountPath: /
      volumes:
      - name: counter-script
        configMap:
          defaultMode: 420
          name: counter-cm
      - name: counter
        persistentVolumeClaim:
          claimName: counter
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi